### ISSUE TITLE
Fixed standard fields names for models

### ISSUE THREAD

**Issue by michaelbag** [michaelbag/remit#5]

**Comment by michaelbag** [comment]
Something from Best Practice... 

Always use lowercase letters and underscores for Django model fields names to prevent case sensitivity issues with database backends. For example, full_name instead of FullName.

**Comment by michaelbag** [comment]
Translations from RU 1C to EN.

https://habr.com/ru/articles/518242/

**Comment by michaelbag** [comment]
# Standardize field naming conventions for common attributes

## Problem
Currently, the project uses inconsistent field naming across different models for common attributes like dates, archive status, deletion marks, and full names. This creates confusion for developers and makes the codebase harder to maintain.

## Solution
Establish and document standardized field naming conventions for common attributes used across the project.

## Proposed Field Naming Standards

### 1. Start Date/Time
**Recommended name:** `start_date`
- **Field type:** `models.DateField` (for dates) or `models.DateTimeField` (for date and time)
- **Parameters:** `default=date.today` or `default=timezone.now`, `null=True`
- **Examples from codebase:** 
  - `start_date` in Resource, Equipment, Employee models
  - `created_datetime` in ExtSystem model

### 2. End Date/Time
**Recommended name:** `end_date`
- **Field type:** `models.DateField` (for dates) or `models.DateTimeField` (for date and time)
- **Parameters:** `null=True`, `blank=True`
- **Examples from codebase:**
  - `end_date` in Resource, Equipment, Employee models
  - `last_ping_datetime` in ExtSystem model

### 3. Archive Status
**Recommended name:** `archive`
- **Field type:** `models.BooleanField`
- **Parameters:** `default=False`, `db_index=True`
- **Examples from codebase:**
  - `archive` in Resource, ResourceGroup, Equipment, Employee, QRCode, Service, Software models

### 4. Deletion Mark
**Recommended name:** `delete_mark`
- **Field type:** `models.BooleanField`
- **Parameters:** `default=False`, `db_index=True`
- **Examples from codebase:**
  - `delete_mark` in base Catalog model and all inheriting models

### 5. Full Name/Title
**Recommended name:** `title`
- **Field type:** `models.CharField`
- **Parameters:** `max_length=150`, `blank=True`
- **Examples from codebase:**
  - `title` in Equipment, ResourceGroup, QRCode, ExtSystem models
  - `name` used for short names
  - `cached_full_path_name` for composite names

## Standard Fields for All Models

### From GUIDModel base class:
```python
guid = models.UUIDField(primary_key=True, default=uuid.uuid4)
modified = models.DateTimeField(editable=False, auto_now=True, db_index=True)
created = models.DateTimeField(editable=False, auto_now_add=True, db_index=True)
```

### From Catalog base class:
```python
code = models.CharField(max_length=9, blank=True, db_index=True)
name = models.CharField(max_length=32, blank=True, db_index=True)
delete_mark = models.BooleanField(default=False, db_index=True)
```

### Business logic specific fields:
```python
# Date fields
start_date = models.DateField(default=date.today, null=True)
end_date = models.DateField(null=True, blank=True)

# Status fields
archive = models.BooleanField(default=False, db_index=True)

# Name fields
title = models.CharField(max_length=150, blank=True, help_text=_('Full title'))
name = models.CharField(max_length=150, blank=True, db_index=True)  # short name
```

## Help Text Standards
```python
start_date = models.DateField(default=date.today, null=True, help_text=_('Start date'))
end_date = models.DateField(null=True, blank=True, help_text=_('End date'))
archive = models.BooleanField(default=False, db_index=True, help_text=_('Is archived'))
delete_mark = models.BooleanField(default=False, db_index=True, help_text=_('Mark for deletion'))
title = models.CharField(max_length=150, blank=True, help_text=_('Full title'))
```

## Implementation Tasks

### Phase 1: Documentation
- [ ] Create field naming standards documentation
- [ ] Update coding guidelines
- [ ] Add examples to developer documentation

### Phase 2: Code Review
- [ ] Audit existing models for compliance
- [ ] Identify models that need field renaming
- [ ] Create migration plan for non-compliant fields

### Phase 3: Migration (if needed)
- [ ] Create database migrations for field renames
- [ ] Update admin configurations
- [ ] Update forms and serializers
- [ ] Update JavaScript and templates
- [ ] Update tests

## Acceptance Criteria
- [ ] All new models follow standardized naming conventions
- [ ] Documentation is created and accessible to developers
- [ ] Existing models are audited for compliance
- [ ] Migration plan is created for non-compliant fields
- [ ] Code review checklist includes naming convention checks

## Benefits
- **Consistency:** Uniform field names across all models
- **Maintainability:** Easier to understand and modify code
- **Developer Experience:** Reduced cognitive load when working with different models
- **Code Quality:** Better adherence to Django best practices

## Files to Review/Update
- `common/models.py` - Base model definitions
- `common/com_models.py` - GUID model base class
- All model files in `apps/*/models.py`
- Admin configurations in `apps/*/admin.py`
- Forms in `apps/*/forms.py`
- Documentation files

## Labels
`documentation` `standards` `refactoring` `maintenance`
